server:
  port: "8081"
  name: "demo1116"
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  database: unicorn_sys
redis:
  host: "127.0.0.1"
  port: "6379"
  password: "123456"
  db: "1"
cache:
  default: redis